"""execlist.py — the execution list, rendered between markers from the tree.

Generated from the same tree `pm status` reads, so it is a view and not a
second scoreboard; V6 fails when it drifts. Order is phase, then Kahn with
a name tiebreak, then name — deterministic, so the diff never churns.
"""
from __future__ import annotations

from pathlib import Path

from agentic_sdlc.core import apply
from agentic_sdlc.repo.pm import model, validate

OPEN = '<!-- pm:execution -->'
CLOSE = '<!-- /pm:execution -->'
NOTE = ('*Generated by `agentic-sdlc pm sync` from the tree — do not edit. '
        '`pm status` is the live read; this is the ORDER.*')


class Refusal(Exception):
    """A grain file this renderer cannot rewrite correctly — not UTF-8, or a
    broken marker pair. Nothing is written.
    """


def _toposort(names: list[str], deps: dict[str, list[str]]) -> list[str]:
    """Kahn, name-tiebroken. A cycle degrades to name order (V5 reports it)."""
    remaining = set(names)
    out: list[str] = []
    while remaining:
        ready = sorted(n for n in remaining
                       if not (set(deps.get(n, ())) & remaining))
        if not ready:                       # cycle — V5 owns that finding
            out.extend(sorted(remaining))
            break
        out.extend(ready)
        remaining -= set(ready)
    return out


def _short(gid: str) -> str:
    return gid.rpartition('/')[2] or gid


def milestone_rows(cfg: model.PmConfig, mdir: Path) -> list[str]:
    mid = model.unquote(model.field_of(mdir / model.MILESTONE_DOC, 'id'))
    views = [model.read_feature(cfg, f)
             for f in model.feature_files(cfg, mid)]
    by_id = {v.fid: v for v in views}
    deps: dict[str, list[str]] = {}
    for v in views:
        try:
            refs = validate._refs(v.path, 'depends_on')
        except validate.Unparseable:
            refs = []
        deps[v.fid] = [r for r in refs if r in by_id]
    # `model.phase_key` is the one reading order of a board; it knows no phase
    # word.
    buckets: dict[tuple, list[str]] = {}
    phases: dict[tuple, str] = {}
    for v in views:
        key = model.phase_key(v.phase)
        buckets.setdefault(key, []).append(v.fid)
        phases[key] = v.phase
    rows, n = [], 0
    for key in sorted(buckets):
        ordered = _toposort(sorted(buckets[key]), deps)
        if len(buckets) > 1 or phases[key]:
            rows.append(f'\n**{model.phase_label(phases[key])}**\n')
        for fid in ordered:
            v = by_id[fid]
            n += 1
            blockers = [_short(d) for d in deps[fid]]
            after = f' — after {", ".join(blockers)}' if blockers else ''
            rows.append(f'{n}. `{_short(fid)}` · {v.status} · '
                        f'{v.done_n}/{v.total} stories{after}')
    return rows


def feature_rows(cfg: model.PmConfig, ffile: Path) -> list[str]:
    stories = model.story_files(
        cfg, model.unquote(model.field_of(ffile, 'id')))
    ids = {model.field_of(s, 'id'): s for s in stories}
    deps: dict[str, list[str]] = {}
    for sid, sfile in ids.items():
        try:
            refs = validate._refs(sfile, 'depends_on')
        except validate.Unparseable:
            refs = []
        deps[sid] = [r for r in refs if r in ids]
    rows = []
    for n, sid in enumerate(_toposort(sorted(ids), deps), 1):
        status = model.field_of(ids[sid], 'status')
        owner = model.field_of(ids[sid], 'owner')
        blockers = [_short(d) for d in deps[sid]]
        after = f' — after {", ".join(blockers)}' if blockers else ''
        who = f' ({owner})' if owner else ''
        rows.append(f'{n}. `{_short(sid)}` · {status}{who}{after}')
    return rows


def block_for(cfg: model.PmConfig, path: Path) -> str:
    rows = (milestone_rows(cfg, path.parent) if path.name == model.MILESTONE_DOC
            else feature_rows(cfg, path))
    body = '\n'.join(rows) if rows else '_(nothing yet)_'
    return f'{OPEN}\n{NOTE}\n\n{body}\n{CLOSE}'


def _replace(text: str, block: str, rel: str) -> str:
    start, end = text.find(OPEN), text.find(CLOSE)
    if start == -1 and end == -1:
        sep = '' if text.endswith('\n\n') else ('\n' if text.endswith('\n') else '\n\n')
        return f'{text}{sep}## Execution order\n\n{block}\n'
    # Half a marker pair is not "no block": appending there grew the file every
    # run.
    if start == -1:
        raise Refusal(f'{rel}: {CLOSE!r} appears without {OPEN!r} — restore '
                      f'the opening marker (or delete the closing one); '
                      f'nothing was written')
    if end == -1:
        raise Refusal(f'{rel}: {OPEN!r} appears without {CLOSE!r} — restore '
                      f'the closing marker (or delete the opening one); '
                      f'nothing was written')
    if end < start:
        raise Refusal(f'{rel}: {CLOSE!r} appears BEFORE {OPEN!r} — the markers '
                      f'are reversed; swap them back, nothing was written')
    return text[:start] + block + text[end + len(CLOSE):]


def targets(cfg: model.PmConfig) -> list[Path]:
    out = []
    for milestone in model.milestones(cfg):
        mdir = milestone.path.parent
        out.append(mdir / model.MILESTONE_DOC)
        out.extend(model.feature_files(cfg, milestone.gid))
    return out


def has_block(text: str) -> bool:
    return OPEN in text and CLOSE in text


def sync(cfg: model.PmConfig, write: bool = True,
         existing_only: bool = False) -> list[tuple[Path, bool]]:
    """Returns (path, changed) per grain file; `write=False` only reports, and
    `existing_only` walks only files that already carry a block (V6's
    case). Raises `Refusal` before any write, naming every unrewritable
    file.
    """
    plans: list[tuple[Path, str, str]] = []
    refusals: list[str] = []
    for path in targets(cfg):
        try:
            before = model.read_raw(path)
        except UnicodeDecodeError as err:
            refusals.append(f'{cfg.rel(path)}: not UTF-8 ({err}) — re-encode '
                            f'it; nothing was written')
            continue
        if existing_only and not has_block(before):
            continue
        try:
            plans.append((path, before, _replace(before, block_for(cfg, path),
                                                 cfg.rel(path))))
        except Refusal as err:
            refusals.append(str(err))
    if refusals:
        raise Refusal('\n'.join(refusals))
    results = []
    for path, before, after in plans:
        changed = after != before
        if changed and write:
            apply.raise_on_error(apply.write(path, after))
        results.append((path, changed))
    return results
