"""skills.py — the pm verbs that install devkit-owned files into the consumer.

`cmd_init`, `cmd_install_skills` and `cmd_templates` are
`repo/install.py`'s concern rather than status verbs, so they live here and
`cli.py` routes. The refusal helpers and the diff printer are single-homed
in `repo/install.py`.
"""
from __future__ import annotations

import sys
from pathlib import Path

from agentic_sdlc.core import apply
from agentic_sdlc.repo import install
from agentic_sdlc.repo.pm import model, templates
from agentic_sdlc.repo.pm.cli import USAGE, Refused, Usage, _ok

GUIDANCE_HEADER = 'GENERATED by agentic-sdlc'

# The SIXTH installer's plan, in the shape `install.PLANS` uses, so the belt's
# census can walk all six verbs rather than the five that happen to live in one
# module (review O2). `cmd_install_skills` reads it too, so the two cannot
# drift apart.
GUIDANCE_PLAN = (
    ('pm-execution.md', '.claude/rules/pm-execution.md'),
    ('pm-operations.md', '.claude/skills/pm-operations/SKILL.md'),
    # A skill, not a rule: nothing path-triggers on "write me a handoff", and a
    # skill description is the only surface that matches the words somebody
    # types. It ROUTES to `pm new handoff` and the template rather than
    # restating either (0.4.0/D6).
    ('handoff.md', '.claude/skills/handoff/SKILL.md'),
)
GUIDANCE_VERB = 'pm install-skills'


def guidance_body(name: str) -> str:
    """The rendered guidance file, version stamp substituted."""
    from importlib import resources
    from agentic_sdlc import __version__
    body = (resources.files('agentic_sdlc.repo.pm.guidance')
            .joinpath(name).read_text(encoding='utf-8'))
    return body.replace('{version}', f'v{__version__}')

def stand_up_tree(cfg: model.PmConfig) -> list[str]:
    """Create the roadmap dir if absent; return what was created. The tree half
    of `pm init`, kept apart from the guidance half because `init` needs only
    this.

    **No `ROADMAP.md` (0.3.0.)** It was two things wearing one name: a
    hand-maintained index of milestones still in the tree — the second
    scoreboard this package forbids one grain down — and the only record of
    what `pm retire` deleted. `pm roadmap` derives the first from the tree, and
    `order` in `releases.md` carries the second, with nobody maintaining it.
    """
    plan = apply.Plan()
    if not cfg.roadmap.is_dir():
        plan.make_dir(cfg.roadmap, label=f'{cfg.roadmap_dir}/')
    apply.raise_on_error(plan.apply(decide=False))
    return [step.label for step in plan.steps]


GITATTRIBUTES = '.gitattributes'
MERGE_UNION = 'merge=union'
# Above the line we add, and only when we are the ones creating the file.
GITATTRIBUTES_HEADER = ('# agentic-sdlc: the pm ledger is append-only, so two '
                        'branches\' rows are a union, never a conflict')


# `**/*.jsonl`, both halves load-bearing. `**` because gitignore-style `a/**/b`
# matches `a/b` too, and the grainless ledger sits at `<roadmap>/ledger.jsonl`
# (D3) — one level short of `<roadmap>/*/`. `*.jsonl` and not the file NAME
# because a pooled milestone's ledger is `<roadmap>/ledgers/<id>.jsonl`, which
# no pattern ending in `ledger.jsonl` reaches — and every branch appends to the
# ledger of the milestone it is building, so the miss is a merge conflict on
# every parallel branch. The fact was never a filename: it is *an append-only
# log under the roadmap*.
GLOB = '**'
LEDGER_GLOB = '*.jsonl'


def attribute_pattern(cfg: model.PmConfig) -> str:
    """The path glob the merge attribute applies to, from the configured `[pm]
    roadmap_dir` — a literal would go inert for a moved tree.
    """
    return f'{cfg.roadmap_dir}/{GLOB}/{LEDGER_GLOB}'


def attribute_line(roadmap_dir: str) -> str:
    """`pm/roadmap/**/*.jsonl merge=union`, spelled in one place — matching
    every home: one ledger per milestone under `ledgers/`, and the tree's own
    for the rows that name no grain."""
    return f'{roadmap_dir}/{GLOB}/{LEDGER_GLOB} {MERGE_UNION}'


def _declares(text: str, pattern: str, line: str) -> str:
    """'exact' | 'other' | '' — what this `.gitattributes` already says about
    the pattern; 'other' is a project opinion to append below, not to fold
    into absent.
    """
    for raw in text.splitlines():
        stripped = raw.strip()
        if not stripped or stripped.startswith('#'):
            continue
        if stripped == line:
            return 'exact'
        if stripped.split()[0] == pattern:
            return 'other'
    return ''


def install_merge_attribute(cfg: model.PmConfig) -> str:
    """Make `<roadmap>/**/*.jsonl merge=union` true; returns what happened.
    The glob reaches every home — one ledger per milestone under `ledgers/`,
    and the tree's own for rows naming no grain (0.4.0/D3). Appends, like the
    `.gitignore` write, because the file already holds project opinions;
    idempotent.
    """
    target = cfg.root / GITATTRIBUTES
    line = attribute_line(cfg.roadmap_dir)
    defect = install.destination_defect(target)
    if defect:
        raise Refused(f'{GITATTRIBUTES} {defect} — the ledger merge attribute '
                      f'was not installed; add `{line}` yourself once the path '
                      f'is writable')
    existing = ''
    if target.is_file():
        text, unreadable = install.read_destination(target)
        if unreadable:
            raise Refused(f'{GITATTRIBUTES} {unreadable} — the ledger merge '
                          f'attribute was not installed')
        existing = text or ''
    state = _declares(existing, attribute_pattern(cfg), line)
    if state == 'exact':
        return f'{GITATTRIBUTES} already carries `{line}`'
    block = line + '\n'
    if existing:
        head = '' if existing.endswith('\n') else '\n'
        body = existing + head + '\n' + block
    else:
        body = GITATTRIBUTES_HEADER + '\n' + block
    result = apply.Plan().overwrite(target, body, newline=None,
                                    label=GITATTRIBUTES).apply(decide=False)
    if result.failed is not None:
        raise Refused(f'{GITATTRIBUTES} could not be written ({result.error}) '
                      f'— add `{line}` yourself')
    said = 'appended to' if existing else 'wrote'
    note = (' (it already declares that path with other attributes — the last '
            'match wins, so this line is the one in force)'
            if state == 'other' else '')
    return f'{said} {GITATTRIBUTES}: {line}{note}'


CONFIG_FILE = 'devkit.toml'
# Above the appended block, so a reader knows which verb put it there.
FLOW_HEADER = ('# --- the flow — appended by `agentic-sdlc pm init` ----------'
               '------------------\n'
               '# Every state this project uses, each in exactly one of '
               'todo / in_progress /\n'
               '# done. Yours: `pm vocabulary` echoes it, every run reads it, '
               'and there is no\n'
               '# default behind it (CLAUDE.md hard rule 5).\n')


def install_flow(cfg: model.PmConfig) -> str:
    """Make `[pm.states.<kind>]` true in devkit.toml; returns what happened.
    Appends, preserving every other byte and the file's line endings;
    idempotent, and a missing devkit.toml is created holding the flow
    alone.
    """
    target = cfg.root / CONFIG_FILE
    if cfg.flows:
        return f'{CONFIG_FILE} already declares [pm.states.*] — left alone'
    defect = install.destination_defect(target)
    if defect:
        raise Refused(f'{CONFIG_FILE} {defect} — the flow was not written; '
                      f'run `agentic-sdlc pm vocabulary` for the section and '
                      f'add it yourself once the path is writable')
    existing = ''
    if target.is_file():
        try:
            existing = model.read_raw(target)
        except (OSError, UnicodeDecodeError) as err:
            raise Refused(f'{CONFIG_FILE} could not be read ({err}) — the '
                          f'flow was not written') from err
    eol = '\r\n' if '\r\n' in existing else '\n'
    block = (FLOW_HEADER + model.render_seed()).replace('\n', eol)
    if existing:
        head = '' if existing.endswith(('\n', '\r')) else eol
        body = existing + head + eol + block
    else:
        body = block
    result = apply.Plan().overwrite(target, body, newline='',
                                    label=CONFIG_FILE).apply(decide=False)
    if result.failed is not None:
        raise Refused(f'{CONFIG_FILE} could not be written ({result.error}) '
                      f'— the flow was not written')
    said = 'appended the flow to' if existing else 'wrote the flow into'
    return (f'{said} {CONFIG_FILE}: [pm.states.'
            f'{"|".join(model.FLOW_KINDS)}]')


def print_ladder() -> None:
    """What was just declared, AGAINST THE TREE: per kind, the states in use
    and the states never held.

    The finding this exists for: an adopting agent hit `check pm` exit 2, ran
    `pm init`, saw `appended the flow to devkit.toml`, watched the gate go green
    and moved on. The states were adopted as a CONFIG FIX and nobody then asked
    whether the tree used them — it used three of eight. Reporting a WRITE and
    reporting a MEANING are different acts, and only the second one teaches the
    conveyor.
    """
    # `install_flow` may have just written the section this counts, so the read
    # has to be against the file as it is NOW. `model.reload` owns the cache
    # drop; a raw `load_config` here would be a second door into the config
    # this package keeps to one.
    try:
        fresh = model.reload()
        # ONE walk of the tree, not one per kind: this reads `field_of` on
        # every grain, and four passes for one report is three too many.
        usage = model.state_usage(fresh)
    except model.ConfigError as err:
        # The flow was just written, so this should not happen — and if it
        # does, saying so beats printing nothing and looking like success.
        print(f'[pm] the flow was written but could not be read back: {err}')
        return
    if not usage:
        return
    print()
    print('The flow this project now declares, against the tree it has:')
    print()
    for kind in model.FLOW_KINDS:
        counts = usage.get(kind)
        if not counts:
            continue
        in_use = [state for state, n in counts.items() if n]
        never = [state for state, n in counts.items() if not n]
        if not in_use:
            # EVERY state unused means the tree holds no grain of this kind —
            # a different fact, and the one a fresh tree is full of. `U1` skips
            # it deliberately (its criterion 4); the ladder must agree, or the
            # consumer meets the misleading surface FIRST, at adoption, when
            # nothing has been written yet.
            print(f'  {kind:<10} declares {len(counts)}; this tree holds no '
                  f'{kind} yet')
            continue
        print(f'  {kind:<10} declares {len(counts)}; this tree uses '
              f'{len(in_use)} ({", ".join(in_use)})')
        if never:
            print(f'  {"":<10} never held: {", ".join(never)}')
    print()
    print('  A state you declare and never use is a flow you are not running.')
    print('  `check pm` U1 keeps saying so after this scrolls away, as a WARN')
    print('  with the count — never a finding, because a tree mid-adoption')
    print('  legitimately has unused states.')


def cmd_init(cfg: model.PmConfig, args: list[str]) -> int:
    """Stand up a PM tree in a repo that has none, flow first, and say what is
    left to do.
    """
    if args:
        raise Usage(USAGE)
    _ok(install_flow(cfg))
    made = stand_up_tree(cfg)
    for m in made:
        _ok(f'created {m}')
    if not made:
        _ok(f'{cfg.roadmap_dir}/ already exists — leaving it alone')
    _ok(install_merge_attribute(cfg))
    cmd_install_skills(cfg, [])
    print_ladder()

    # The rest is the consumer's to wire; printing it beats a README they must
    # find.
    print()
    print('Next, in your own repo:')
    print()
    print('  1. Add `pm` to the gate roster your per-change set runs:')
    print()
    print('       [checks]')
    print('       all = ["doc", "shell", "pm"]')
    print()
    print('  2. Declare any schema differences in devkit.toml (all optional):')
    print()
    print('       [pm]')
    print('       review_dir = "docs/reviews"   # where review records live')
    print('       # milestone_dir = "..."       # else <roadmap_dir>/milestones,')
    print('                                    # and the same for feature/story/'
          'bug/ledger')
    print('       # checks = [...]              # add D9/D10 for'
          ' branch-per-milestone,')
    print('                                    # R5 to grade the version file'
          ' against the plan')
    print()
    print('  3. Scaffold your first milestone, then check it:')
    print()
    print('       agentic-sdlc pm new milestone first-light "First Milestone" '
          '--version 0.1')
    print('       agentic-sdlc pm validate')
    print()
    print('  4. Keep your OWN vocabulary local — what a milestone means here, which')
    print('     surfaces exist, who reviews what. The two installed files carry only')
    print('     what the CLI enforces and explains.')
    return 0


def cmd_install_skills(cfg: model.PmConfig, args: list[str]) -> int:
    """Write the execution-loop guidance into the consuming repo as an
    auto-loading rule; only what the CLI itself enforces ships here.
    """
    force = False
    diff = False
    for a in args:
        if a == '--force':
            force = True
        elif a == '--diff':
            diff = True
        else:
            raise Usage(f'unknown flag {a!r}')

    from importlib import resources
    from agentic_sdlc import __version__

    # (source markdown, destination): the rule auto-loads on any tree edit; the
    # skill is invoked deliberately.
    plan = [(name, cfg.root / rel) for name, rel in GUIDANCE_PLAN]
    # Decided for both entries before either is written, so "nothing was
    # written" is true of the whole command; --diff prints off the same helper
    # the install-* verbs use.
    if diff:
        for name, target in plan:
            body = (resources.files('agentic_sdlc.repo.pm.guidance')
                    .joinpath(name).read_text(encoding='utf-8'))
            install.print_diff(cfg.rel(target), target,
                               body.replace('{version}', f'v{__version__}'))
        return 0

    actions: list[tuple[str, Path, str]] = []
    collisions: list[str] = []
    defects: list[str] = []
    for name, target in plan:
        body = (resources.files('agentic_sdlc.repo.pm.guidance')
                .joinpath(name).read_text(encoding='utf-8'))
        body = body.replace('{version}', f'v{__version__}')
        # A directory, unwritable or undecodable destination is a refusal
        # naming the path, never a traceback with one file already on disk.
        defect = install.destination_defect(target)
        if defect:
            defects.append(f'{cfg.rel(target)} {defect}')
            continue
        if target.is_file():
            existing, unreadable = install.read_destination(target)
            if unreadable:
                defects.append(f'{cfg.rel(target)} {unreadable}')
                continue
            if existing == body:
                actions.append(('current', target, body))
                continue
            # A file we did not generate, or one somebody edited, is theirs.
            if (existing is None
                    or GUIDANCE_HEADER not in existing) and not force:
                collisions.append(cfg.rel(target))
                continue
        actions.append(('write', target, body))
    if collisions:
        head, tail = install.collision_refusal(collisions)
        raise Refused(f'{head}\n{tail}')
    if defects:
        raise Refused(f'{len(defects)} destination(s) cannot be written:\n'
                      + '\n'.join(f'    {d}' for d in defects)
                      + '\nNothing was written. Fix the path(s) and re-run — '
                        'the command is idempotent.')

    # One plan: destinations decided above, `core.apply` reports which landed.
    writes = apply.Plan()
    for kind, target, body in actions:
        if kind != 'current':
            writes.overwrite(target, body, newline=None, label=cfg.rel(target))
    result = writes.apply(decide=False)
    written = [step.label for step in result.landed]
    landed = set(written)
    # Review I2: this is the SIXTH installer (CLAUDE.md's self-hosting list) and
    # its per-file lines carry the prefix the report criterion is about, so
    # `grep '^[install]'` answers for every file the package installs rather
    # than for five verbs out of six.
    #
    # Review I3: NOT REACHED, never `break`. Dropping the tail after a failed
    # write is the same silence — a file the run never got to is a fact the
    # reader needs, and `install.py` already named it for exactly this case.
    for kind, target, body in actions:
        rel = cfg.rel(target)
        if kind == 'current':
            install._say(install.IS_CURRENT.format(rel=rel))
        elif rel in landed:
            install._say(f'wrote {rel}')
        else:
            install._say(install.NOT_REACHED.format(rel=rel))
    if result.failed is not None:
        raise Refused(
            f'{result.failed.label} could not be written '
            f'({result.error}) — '
            + ('nothing was written' if not written else
               'ALREADY WRITTEN before this was reached: '
               + ', '.join(written))
            + '. Fix the path and re-run — the command is idempotent.')
    wrote = len(written)
    if wrote:
        _ok(f'agentic-sdlc v{__version__} — these carry only what the pm CLI '
            f'itself enforces and explains. Your project\'s SDLC (branching, '
            f'versioning, release, dispatch, review rosters) stays in your own '
            f'rules and agents.')
    return 0


def cmd_templates(cfg: model.PmConfig, args: list[str]) -> int:
    """Copy the packaged templates into the project so they can be edited."""
    force = '--force' in args
    for a in args:
        if a != '--force':
            raise Usage(f'unknown flag {a!r}')
    try:
        written, variants = templates.install(cfg, force)
    except templates.MissingTemplate as err:
        raise Usage(str(err)) from err
    for path in written:
        _ok(f'installed {cfg.rel(path)}')
    for other, slot in variants:
        _ok(f'{cfg.template_dir}/{other} is a case variant of {slot} and was '
            f'NOT written past — the loader reads EXACT names, so that file is '
            f'never used; `git mv --force {cfg.template_dir}/{other} '
            f'{cfg.template_dir}/{slot}`, then re-run')
    if not written:
        _ok(f'{cfg.template_dir}/ already populated (--force to overwrite)')
    return 0


CONFIG_SEED_FLAG = '--seed'
CONFIG_USAGE = """usage: agentic-sdlc pm config --seed

Prints the seed devkit.toml THIS PINNED TOOL ships — every gate key commented
at the default the code actually holds, and the two declarations spelled out
with their arguments. Emits the file, not columns, and writes nothing.

`init` serves a new repo once; this serves every bump after it, which is where
a consumer spends the rest of the tool's life. Diff it against your own
devkit.toml to see what a version added, renamed or retired."""


def cmd_config(cfg: model.PmConfig, args: list[str]) -> int:
    """`pm config --seed` — the shipped seed on stdout, byte for byte."""
    if args and args[0] in ('-h', '--help'):
        print(CONFIG_USAGE)
        return 0
    if args != [CONFIG_SEED_FLAG]:
        raise Usage(CONFIG_USAGE)
    # Deferred: `repo.init` reaches back into this module for the PM tree.
    from agentic_sdlc.repo import init
    sys.stdout.write(init.seed_body(init.SEED_CONFIG[0]))
    return 0
